AWSTemplateFormatVersion: 2010-09-09
Description: EC2 instance with EBS volume attached. Project 1 SysOps Learning
Parameters:
    Stage:
        Type: String
        Default: Development
        AllowedValues:
            - Development
            - Production
            - Staging
    InstanceName:
        Type: String
        Default: ec2-instance-alpha
    SubnetId:
        Type: String
        Description: Subnet ID for the EC2 instance
    SecurityGroupId:
        Type: String
        Description: Security group ID for the EC2 instance
    AmiId:
        Type: String
        Description: AMI ID for the EC2 instance
    AvailabilityZone:
        Type: String
        Description: Availability zone

Resources:
    EC2InstanceAlpha:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: !Ref AmiId
            InstanceType: t2.micro
            Tags:
                - Key: Name
                  Value: !Ref InstanceName
                - Key: Stage
                  Value: !Ref Stage
            SubnetId: !Ref SubnetId
            SecurityGroupIds:
                - !Ref SecurityGroupId
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 10
                      VolumeType: gp2
                      DeleteOnTermination: true

    EBSVolumeAlpha:
        Type: AWS::EC2::Volume
        Properties:
            Size: 10
            AvailabilityZone: !GetAtt EC2InstanceAlpha.AvailabilityZone
            Tags:
                - Key: Name
                  Value: !Ref InstanceName
                - Key: Stage
                  Value: !Ref Stage
            VolumeType: gp2

    VolumeAttachmentAlpha:
        Type: AWS::EC2::VolumeAttachment
        Properties:
            InstanceId: !Ref EC2InstanceAlpha
            VolumeId: !Ref EBSVolumeAlpha
            Device: /dev/sdh
